"""Reusable CSV, PDF, and interactive HTML report export functions."""

from __future__ import annotations

import html
import logging
from datetime import datetime
from pathlib import Path

import pandas as pd
from markdown_it import MarkdownIt


LOGGER = logging.getLogger(__name__)
REQUIRED_FILES = ("cleaned_data.csv", "summary_report.pdf", "interactive_report.html", "README.md")


def markdown_to_html(summary_text: str) -> str:
    """Convert markdown summary text to a styled HTML fragment."""
    return MarkdownIt("commonmark", {"breaks": True}).render(summary_text or "")


def _metadata_readme(df: pd.DataFrame, generated_at: datetime) -> str:
    date_columns = [column for column in df.columns if "date" in column.lower() or "time" in column.lower()]
    date_range = "No date-like column detected."
    if date_columns:
        column = date_columns[0]
        values = pd.to_datetime(df[column], errors="coerce").dropna()
        if not values.empty:
            date_range = f"{column}: {values.min().date()} through {values.max().date()}"
    return "\n".join([
        "# Generated Analysis Report",
        "",
        f"- Generation timestamp: {generated_at.isoformat()}",
        f"- Record count: {len(df):,}",
        f"- Columns: {', '.join(map(str, df.columns))}",
        f"- Data range: {date_range}",
        "- Source: data/raw/customer_correlation_data.csv",
        "",
        "This folder was generated by `export_analysis`; the CSV, PDF, and HTML files use the same analysis run.",
    ])


def _write_pdf(summary_html: str, destination: Path) -> None:
    try:
        from weasyprint import HTML
        document = f"""<!doctype html><html><head><meta charset='utf-8'><style>
        body {{ font-family: Arial, sans-serif; margin: 36px; color: #172033; }}
        h1, h2 {{ color: #0f766e; }} li {{ margin: 8px 0; }}
        </style></head><body><h1>Customer Analysis Report</h1>{summary_html}</body></html>"""
        HTML(string=document).write_pdf(str(destination))
        return
    except (ImportError, OSError) as weasyprint_error:
        LOGGER.warning("WeasyPrint unavailable; using fpdf2 fallback: %s", weasyprint_error)
    try:
        from fpdf import FPDF
    except ImportError as error:
        raise RuntimeError("PDF export requires WeasyPrint or fpdf2; install the declared PDF dependencies.") from error
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Customer Analysis Report")
    pdf.ln(14)
    pdf.set_font("Helvetica", size=10)
    plain_text = summary_html.replace("<", " <").replace(">", "> ")
    plain_text = " ".join(plain_text.split())
    pdf.multi_cell(0, 6, plain_text)
    pdf.output(str(destination))


def _write_interactive_html(summary_text: str, charts_dict: dict, destination: Path) -> None:
    chart_sections = []
    for name, figure in (charts_dict or {}).items():
        if figure is None or not hasattr(figure, "to_html"):
            LOGGER.warning("Skipping invalid chart %r", name)
            continue
        chart_sections.append(f"<section><h2>{html.escape(str(name))}</h2>{figure.to_html(full_html=False, include_plotlyjs=False)}</section>")
    if not chart_sections:
        raise ValueError("No valid Plotly charts were supplied")
    chart_html = "\n".join(chart_sections)
    plotly_script = "https://cdn.plot.ly/plotly-latest.min.js"
    document = f"""<!doctype html><html><head><meta charset='utf-8'><title>Customer Analysis Report</title>
    <script src='{plotly_script}'></script><style>body{{font-family:Arial,sans-serif;margin:32px;background:#f8fafc;color:#172033}}section{{background:white;padding:18px;margin:18px 0;border-radius:8px}}h1{{color:#0f766e}}</style></head>
    <body><h1>Customer Analysis Report</h1><section><h2>Executive Summary</h2>{markdown_to_html(summary_text)}</section>{chart_html}</body></html>"""
    destination.write_text(document, encoding="utf-8")


def export_analysis(df: pd.DataFrame, summary_text: str, charts_dict: dict, output_dir: str | Path) -> Path:
    """Export one analysis run and return its timestamped report directory."""
    if not isinstance(df, pd.DataFrame) or df.empty:
        raise ValueError("Cannot export a missing or empty analysis DataFrame")
    generated_at = datetime.now().astimezone()
    report_root = Path(output_dir)
    report_root.mkdir(parents=True, exist_ok=True)
    report_name = generated_at.strftime("%Y-%m-%d_%H%M_analysis")
    report_dir = report_root / report_name
    suffix = 1
    while report_dir.exists():
        report_dir = report_root / f"{report_name}_{suffix}"
        suffix += 1
    report_dir.mkdir(parents=True, exist_ok=False)
    try:
        df.to_csv(report_dir / "cleaned_data.csv", index=False)
        _write_pdf(markdown_to_html(summary_text), report_dir / "summary_report.pdf")
        _write_interactive_html(summary_text, charts_dict, report_dir / "interactive_report.html")
        (report_dir / "README.md").write_text(_metadata_readme(df, generated_at), encoding="utf-8")
    except Exception:
        LOGGER.exception("Report export failed in %s", report_dir)
        raise
    return report_dir


def verify_export(report_dir: str | Path) -> pd.DataFrame:
    """Verify required report files, sizes, and CSV readability."""
    directory = Path(report_dir)
    rows = []
    for filename in REQUIRED_FILES:
        path = directory / filename
        exists = path.is_file()
        size = path.stat().st_size if exists else 0
        readable = exists and size > 0
        detail = ""
        if filename == "cleaned_data.csv" and exists:
            try:
                frame = pd.read_csv(path)
                readable = not frame.empty
                detail = f"rows={len(frame)}, columns={len(frame.columns)}"
            except Exception as error:
                readable = False
                detail = str(error)
        rows.append({"file": filename, "exists": exists, "size_bytes": size, "readable": readable, "status": "PASS" if exists and readable else "FAIL", "detail": detail})
    return pd.DataFrame(rows)